name = x_mob_core
title = X Mob Core
description = High-performance, zero-dependency S.O.L.I.D. mob and spawner framework for Luanti
depends =
optional_depends =
min_minetest_version = 5.17.0
author = SaKeL
release = 1000
