name = x_mob_core
title = X Mob Core
description = High-performance, zero-dependency S.O.L.I.D. mob and spawner framework for Luanti
depends =
optional_depends = player_monoids, pova, playerphysics, stamina, hbhunger, hunger_ng, x_player_api, player_api, x_player_armor
min_minetest_version = 5.17.0
author = SaKeL
